#!/usr/bin/env python3
"""Generates seed.sql — deterministic sample data for the Custody Data Lab.
Run once if you want to change the data:  python3 make_seed.py > seed.sql
Business dates: Mon 7 Sep 2026 .. Fri 11 Sep 2026 (as-of date = 2026-09-11)."""
import datetime as dt, random
random.seed(42)

out = []
def w(s=""): out.append(s)
def q(v):
    if v is None: return "NULL"
    if isinstance(v, bool): return "TRUE" if v else "FALSE"
    if isinstance(v, (int, float)): return repr(v)
    return "'" + str(v).replace("'", "''") + "'"
def ins(table, rows):
    w(f"-- {table}: {len(rows)} rows")
    for r in rows: w(f"INSERT INTO {table} VALUES ({', '.join(q(v) for v in r)});")
    w()

w("-- Generated by make_seed.py — sample data for the Custody Data Lab (fictional clients).")
w()

clients = [
 ("C-MERIDIAN","Meridian Pension Trust","Pension fund","GB","Priya Nair"),
 ("C-HALCYON","Halcyon Asset Management","Asset manager","US","Tom Whitfield"),
 ("C-ORIENT","Orient Mutual Insurance","Insurer","JP","Aiko Tanaka"),
]
ins("dim_client", clients)

accounts = [
 ("A-1001","C-MERIDIAN","MER-EQ-01","Meridian Global Equity","USD","Custody","Meridian Pension Trustees Ltd"),
 ("A-1002","C-MERIDIAN","MER-FI-01","Meridian Global Bond","USD","Custody","Meridian Pension Trustees Ltd"),
 ("A-1003","C-MERIDIAN","MER-CASH","Meridian Cash Sweep","USD","Cash","Meridian Pension Trustees Ltd"),
 ("A-2001","C-HALCYON","HAL-ETF-01","Halcyon US Large Cap ETF","USD","Fund","Halcyon Funds Inc"),
 ("A-2002","C-HALCYON","HAL-INC-01","Halcyon Income Fund","USD","Fund","Halcyon Funds Inc"),
 ("A-3001","C-ORIENT","ORI-GEN-01","Orient General Account","JPY","Custody","Orient Mutual Insurance KK"),
]
ins("dim_account", accounts)

securities = [
 ("S-US-AAPL","US0378331005","AAPL","Apple Inc","Equity","US","USD","DTC"),
 ("S-US-MSFT","US5949181045","MSFT","Microsoft Corp","Equity","US","USD","DTC"),
 ("S-JP-7203","JP3633400001","7203","Toyota Motor Corp","Equity","JP","JPY","JASDEC"),
 ("S-DE-SAP","DE0007164600","SAP","SAP SE","Equity","DE","EUR","Clearstream"),
 ("S-US-T34","US91282CJZ59","T 2.5 34","US Treasury 2.5% 2034","Government Bond","US","USD","Fedwire"),
 ("S-DE-BUND31","DE0001102572","BUND 31","Bund 0.5% 2031","Government Bond","DE","EUR","Clearstream"),
 ("S-GB-GILT35","GB00BMBL1F74","GILT 35","UK Gilt 4.25% 2035","Government Bond","GB","GBP","CREST"),
 ("S-US-IBM28","US459200JQ59","IBM 28","IBM 3.3% 2028","Corporate Bond","US","USD","DTC"),
 ("S-US-TBILL","US912797LM10","T-BILL","US T-Bill 3M","Cash Equivalent","US","USD","Fedwire"),
]
ins("dim_security", securities)

# dates: 1 Sep .. 30 Sep 2026
dates = []
d = dt.date(2026, 9, 1)
while d <= dt.date(2026, 9, 30):
    bd = d.weekday() < 5 and d != dt.date(2026, 9, 7)  # 7 Sep 2026 = US Labor Day (holiday)
    dates.append((d.isoformat(), d.year, (d.month-1)//3+1, d.month, d.strftime("%B"), d.strftime("%A"), bd, d == dt.date(2026, 9, 30)))
    d += dt.timedelta(days=1)
ins("dim_date", dates)

funds = [
 ("F-HAL-ETF","Halcyon US Large Cap ETF","C-HALCYON","ETF","16:00"),
 ("F-HAL-INC","Halcyon Income Fund","C-HALCYON","Mutual fund","18:00"),
]
ins("dim_fund", funds)

# ---- positions: business days 8-11 Sep plus 4 Sep, for trend queries
biz = ["2026-09-04","2026-09-08","2026-09-09","2026-09-10","2026-09-11"]
base_px = {"S-US-AAPL":209.5,"S-US-MSFT":418.2,"S-JP-7203":2890.0,"S-DE-SAP":198.4,
           "S-US-T34":97.85,"S-DE-BUND31":91.20,"S-GB-GILT35":99.10,"S-US-IBM28":98.40,"S-US-TBILL":99.05}
fx = {"USD":1.0,"JPY":0.00682,"EUR":1.084,"GBP":1.272}
ccy = {s[0]:s[6] for s in securities}
holdings = {
 "A-1001":{"S-US-AAPL":120000,"S-US-MSFT":95000,"S-JP-7203":800000,"S-DE-SAP":150000,"S-US-TBILL":60000},
 "A-1002":{"S-US-T34":220000000,"S-DE-BUND31":155000000,"S-GB-GILT35":90000000,"S-US-IBM28":80000000},
 "A-1003":{"S-US-TBILL":900000},
 "A-2001":{"S-US-AAPL":410000,"S-US-MSFT":260000},
 "A-2002":{"S-US-T34":150000000,"S-US-IBM28":120000000,"S-US-TBILL":200000},
 "A-3001":{"S-JP-7203":2500000,"S-US-T34":50000000},
}
coupon = {"S-US-T34":2.5,"S-DE-BUND31":0.5,"S-GB-GILT35":4.25,"S-US-IBM28":3.3}
positions = []
drift = {s:1.0 for s in base_px}
for i, day in enumerate(biz):
    for s in base_px:
        drift[s] *= 1 + random.uniform(-0.012, 0.014)
    for acct, hold in holdings.items():
        for s, qty in hold.items():
            px = round(base_px[s]*drift[s], 4)
            f = fx[ccy[s]]
            is_bond = s in coupon or s == "S-US-TBILL"
            mv = round(qty * px/100 * f, 2) if is_bond else round(qty * px * f, 2)
            acc = round(qty * coupon[s]/100 * f * (72+i)/365, 2) if s in coupon else 0.0
            loaded = f"{day} 04:{10+i*3:02d}:00" if not (day=="2026-09-11" and acct=="A-3001") else f"{day} 06:52:00"
            src = "CUSTODY_CORE" if acct != "A-3001" else "SUBCUST_JP"
            positions.append((day, acct, s, qty, px, f, mv, acc, src, loaded))
ins("fact_positions", positions)

txns = [
 (1,"A-1001","2026-09-01","2026-09-01","INJECTION","USD",5000000.00,"Opening cash injection from trustee"),
 (2,"A-1001","2026-09-02","2026-09-03","BUY","USD",-2095000.00,"Buy 10,000 AAPL @ 209.50"),
 (3,"A-1001","2026-09-04","2026-09-04","DIVIDEND","USD",30000.00,"AAPL dividend 0.25/sh on 120,000"),
 (4,"A-1001","2026-09-08","2026-09-09","BUY","USD",-1254600.00,"Buy 3,000 MSFT @ 418.20"),
 (5,"A-1001","2026-09-09","2026-09-09","FX","USD",-412300.00,"FX settle EURUSD for SAP purchase"),
 (6,"A-1001","2026-09-10","2026-09-10","FEE","USD",-18250.00,"Q3 safekeeping fee"),
 (7,"A-1001","2026-09-11","2026-09-12","SELL","USD",578000.00,"Sell 200 Toyota lots"),
 (8,"A-1002","2026-09-01","2026-09-01","INJECTION","USD",12000000.00,"Opening cash injection"),
 (9,"A-1002","2026-09-03","2026-09-03","COUPON","USD",1912500.00,"UK Gilt 4.25% semi-annual coupon"),
 (10,"A-1002","2026-09-08","2026-09-09","BUY","USD",-9785000.00,"Buy 10m US Treasury 2.5% 34 @ 97.85"),
 (11,"A-1002","2026-09-10","2026-09-11","BUY","USD",-4560000.00,"Buy 5m Bund 0.5% 31 @ 91.20"),
 (12,"A-1003","2026-09-01","2026-09-01","INJECTION","USD",25000000.00,"Sweep account funding"),
 (13,"A-1003","2026-09-11","2026-09-11","FEE","USD",-2100.00,"Sweep programme fee"),
 (14,"A-2001","2026-09-09","2026-09-10","SELL","USD",4190000.00,"Sell 20,000 AAPL (redemption funding)"),
 (15,"A-3001","2026-09-10","2026-09-12","BUY","USD",-1976000.00,"Buy 100,000 Toyota @ 2890 JPY"),
]
ins("fact_transactions", txns)

trades = [
 ("T-90001","A-1001","S-US-AAPL","BUY",10000,"2026-09-02","2026-09-03","2026-09-03","SETTLED",None,"Goldman Sachs","2026-09-02 17:42:00"),
 ("T-90002","A-1001","S-US-MSFT","BUY",3000,"2026-09-08","2026-09-09","2026-09-09","SETTLED",None,"Morgan Stanley","2026-09-08 16:05:00"),
 ("T-90003","A-1001","S-DE-SAP","BUY",2000,"2026-09-09","2026-09-11",None,"FAILED","COUNTERPARTY_INSUFFICIENT_SECURITIES","Deutsche Bank","2026-09-09 15:30:00"),
 ("T-90004","A-1001","S-JP-7203","SELL",20000,"2026-09-11","2026-09-14",None,"AFFIRMED",None,"Nomura","2026-09-11 09:12:00"),
 ("T-90005","A-1002","S-US-T34","BUY",10000000,"2026-09-08","2026-09-09","2026-09-09","SETTLED",None,"JP Morgan","2026-09-08 18:20:00"),
 ("T-90006","A-1002","S-DE-BUND31","BUY",5000000,"2026-09-10","2026-09-11",None,"FAILED","INSUFFICIENT_CASH_EUR","BNP Paribas","2026-09-10 14:55:00"),
 ("T-90007","A-1002","S-GB-GILT35","SELL",3000000,"2026-09-11","2026-09-14",None,"MATCHED",None,"Barclays",None),
 ("T-90008","A-2001","S-US-AAPL","SELL",20000,"2026-09-09","2026-09-10","2026-09-10","SETTLED",None,"Citadel Securities","2026-09-09 19:48:00"),
 ("T-90009","A-2001","S-US-MSFT","BUY",5000,"2026-09-11","2026-09-14",None,"PENDING",None,"Jane Street","2026-09-11 21:40:00"),
 ("T-90010","A-2002","S-US-IBM28","BUY",4000000,"2026-09-10","2026-09-11","2026-09-11","SETTLED",None,"Bank of America","2026-09-10 12:10:00"),
 ("T-90011","A-3001","S-JP-7203","BUY",100000,"2026-09-10","2026-09-12",None,"FAILED","SSI_MISMATCH","Daiwa","2026-09-10 08:30:00"),
 ("T-90012","A-3001","S-US-T34","BUY",5000000,"2026-09-11","2026-09-14",None,"PENDING",None,"JP Morgan",None),
]
ins("fact_trades", trades)

cas = [
 ("CA-5001","A-1001","S-US-AAPL","CASH_DIVIDEND",False,"2026-08-20","2026-09-04",None,None,"N/A",120000,30000.00),
 ("CA-5001","A-2001","S-US-AAPL","CASH_DIVIDEND",False,"2026-08-20","2026-09-04",None,None,"N/A",410000,102500.00),
 ("CA-5002","A-1001","S-DE-SAP","TENDER_OFFER",True,"2026-09-03","2026-09-05","2026-09-15","2026-09-17","PENDING",150000,4100000.00),
 ("CA-5003","A-1001","S-JP-7203","DIVIDEND_OPTION",True,"2026-09-01","2026-09-10","2026-09-12","2026-09-16","PENDING",800000,360000.00),
 ("CA-5003","A-3001","S-JP-7203","DIVIDEND_OPTION",True,"2026-09-01","2026-09-10","2026-09-12","2026-09-16","ELECTED",2500000,1125000.00),
 ("CA-5004","A-1002","S-DE-BUND31","COUPON",False,"2026-09-01","2026-09-11",None,None,"N/A",155000000,420000.00),
 ("CA-5005","A-2002","S-US-IBM28","TENDER_OFFER",True,"2026-08-28","2026-09-02","2026-09-10","2026-09-12","DEFAULTED",120000000,2700000.00),
 ("CA-5006","A-1001","S-US-MSFT","STOCK_SPLIT",False,"2026-09-08","2026-09-25",None,None,"N/A",95000,0.00),
 ("CA-5007","A-1002","S-GB-GILT35","RIGHTS_ISSUE",True,"2026-09-10","2026-09-11","2026-09-18","2026-09-22","PENDING",90000000,650000.00),
]
ins("fact_corporate_actions", cas)

navs = []
for f, shares, assets0, liab in [("F-HAL-ETF",42000000,1988000000.0,6200000.0),("F-HAL-INC",18500000,463000000.0,1900000.0)]:
    a = assets0
    for i, day in enumerate(biz):
        bench = round(random.uniform(-0.9, 1.1), 4)
        a = round(a * (1 + bench/100 + random.uniform(-0.05, 0.05)/100), 2)
        nav = round((a - liab)/shares, 4)
        if day == "2026-09-11" and f == "F-HAL-INC":
            navs.append((f, day, a, liab, shares, nav, None, "IN_REVIEW", bench))
        elif day == "2026-09-10" and f == "F-HAL-ETF":
            # a bad price feed: fund moved far more than its market — the classic NAV sanity-check catch
            navs.append((f, day, round(a*1.014,2), liab, shares, round((a*1.014-liab)/shares,4), f"{day} 22:41:00", "PUBLISHED", bench))
        else:
            navs.append((f, day, a, liab, shares, nav, f"{day} 19:{5+i*7:02d}:00", "PUBLISHED", bench))
ins("fact_nav", navs)


# ============ DIGITAL EXPERIENCE EXTENSION (JD R-790937 capabilities) ============
users = [
 ("U-101","C-MERIDIAN","Hannah Okafor","Ops analyst","EMEA","CLIENT_IDP",True,"ACTIVE","2026-09-11 07:58:00"),
 ("U-102","C-MERIDIAN","Ben Carter","Ops analyst","EMEA","CLIENT_IDP",True,"ACTIVE","2026-09-11 08:14:00"),
 ("U-103","C-MERIDIAN","Sarah Lindqvist","Treasurer","EMEA","CLIENT_IDP",True,"ACTIVE","2026-09-10 16:40:00"),
 ("U-104","C-MERIDIAN","David Mensah","Client admin","EMEA","CLIENT_IDP",True,"ACTIVE","2026-09-09 11:05:00"),
 ("U-105","C-MERIDIAN","Rachel Byrne","Executive","EMEA","CLIENT_IDP",False,"DORMANT","2026-05-02 09:30:00"),
 ("U-201","C-HALCYON","Miguel Alvarez","Ops analyst","AMER","STATE_STREET_LOCAL",True,"ACTIVE","2026-09-11 13:02:00"),
 ("U-202","C-HALCYON","Jess Park","Portfolio manager","AMER","STATE_STREET_LOCAL",False,"ACTIVE","2026-09-11 09:47:00"),
 ("U-203","C-HALCYON","Owen Reilly","Client admin","AMER","STATE_STREET_LOCAL",True,"ACTIVE","2026-09-08 15:22:00"),
 ("U-204","C-HALCYON","Priya Raman","Ops analyst","AMER","STATE_STREET_LOCAL",True,"DISABLED","2026-06-30 17:00:00"),
 ("U-301","C-ORIENT","Kenji Watanabe","Ops analyst","APAC","CLIENT_IDP",True,"ACTIVE","2026-09-11 01:15:00"),
 ("U-302","C-ORIENT","Yuki Sato","Treasurer","APAC","CLIENT_IDP",True,"ACTIVE","2026-09-10 02:40:00"),
 ("U-303","C-ORIENT","Aiko Tanaka (RM)","Client admin","APAC","STATE_STREET_LOCAL",False,"ACTIVE","2026-09-11 00:50:00"),
]
ins("dim_user", users)

ents = [
 ("U-101","A-1001","VIEW","2026-01-12 10:00:00","ONBOARDING","2026-12-31"),
 ("U-101","A-1001","INSTRUCT","2026-01-12 10:00:00","ONBOARDING","2026-12-31"),
 ("U-101","A-1002","VIEW","2026-01-12 10:00:00","ONBOARDING","2026-12-31"),
 ("U-102","A-1001","VIEW","2026-03-03 09:30:00","U-104","2026-12-31"),
 ("U-102","A-1002","VIEW","2026-03-03 09:30:00","U-104","2026-12-31"),
 ("U-102","A-1002","INSTRUCT","2026-03-03 09:30:00","U-104","2026-12-31"),
 ("U-103","A-1003","VIEW","2026-01-12 10:00:00","ONBOARDING",None),
 ("U-103","A-1003","INSTRUCT","2026-01-12 10:00:00","ONBOARDING",None),
 ("U-104","A-1001","ADMIN","2026-01-12 10:00:00","ONBOARDING",None),
 ("U-104","A-1002","ADMIN","2026-01-12 10:00:00","ONBOARDING",None),
 ("U-104","A-1003","ADMIN","2026-01-12 10:00:00","ONBOARDING",None),
 ("U-105","A-1001","VIEW","2025-11-20 14:00:00","U-104","2026-06-30"),
 ("U-105","A-1002","VIEW","2025-11-20 14:00:00","U-104","2026-06-30"),
 ("U-201","A-2001","VIEW","2025-08-01 09:00:00","ONBOARDING",None),
 ("U-201","A-2002","VIEW","2025-08-01 09:00:00","ONBOARDING",None),
 ("U-202","A-2001","VIEW","2025-08-01 09:00:00","ONBOARDING",None),
 ("U-202","A-2001","INSTRUCT","2026-02-14 11:00:00","U-203",None),
 ("U-202","A-2001","ADMIN","2026-02-14 11:00:00","U-203",None),
 ("U-203","A-2001","ADMIN","2025-08-01 09:00:00","ONBOARDING",None),
 ("U-203","A-2002","ADMIN","2025-08-01 09:00:00","ONBOARDING",None),
 ("U-204","A-2002","VIEW","2025-08-01 09:00:00","ONBOARDING",None),
 ("U-204","A-2002","INSTRUCT","2025-08-01 09:00:00","ONBOARDING",None),
 ("U-301","A-3001","VIEW","2026-04-01 03:00:00","ONBOARDING","2027-03-31"),
 ("U-301","A-3001","INSTRUCT","2026-04-01 03:00:00","ONBOARDING","2027-03-31"),
 ("U-302","A-3001","VIEW","2026-04-01 03:00:00","ONBOARDING","2027-03-31"),
 ("U-303","A-3001","ADMIN","2026-04-01 03:00:00","ONBOARDING",None),
 ("U-303","A-1001","VIEW","2026-08-20 05:10:00","U-303",None),   # cross-client grant: an RM gave herself another client's account
]
ins("fact_user_entitlements", ents)

alerts = [
 (1,"C-MERIDIAN","U-101","A-1001","SETTLEMENT_FAIL","CRITICAL","PORTAL","T-90003","2026-09-11 06:05:00","2026-09-11 06:05:01","2026-09-11 08:02:00"),
 (2,"C-MERIDIAN","U-101","A-1001","SETTLEMENT_FAIL","CRITICAL","EMAIL","T-90003","2026-09-11 06:05:00","2026-09-11 06:05:04",None),
 (3,"C-MERIDIAN","U-102","A-1002","SETTLEMENT_FAIL","CRITICAL","PORTAL","T-90006","2026-09-11 06:05:00","2026-09-11 06:05:01",None),
 (4,"C-MERIDIAN","U-103","A-1002","CASH_SHORTFALL","CRITICAL","EMAIL","T-90006","2026-09-10 17:30:00","2026-09-10 17:30:03","2026-09-11 08:45:00"),
 (5,"C-MERIDIAN","U-101","A-1001","CA_DEADLINE","HIGH","PORTAL","CA-5003","2026-09-09 07:00:00","2026-09-09 07:00:01",None),
 (6,"C-MERIDIAN","U-101","A-1001","CA_DEADLINE","HIGH","EMAIL","CA-5003","2026-09-10 07:00:00","2026-09-10 07:00:02",None),
 (7,"C-MERIDIAN","U-101","A-1001","CA_DEADLINE","CRITICAL","SMS","CA-5003","2026-09-11 07:00:00",None,None),   # SMS delivery failed
 (8,"C-MERIDIAN","U-101","A-1001","CA_DEADLINE","HIGH","PORTAL","CA-5002","2026-09-08 07:00:00","2026-09-08 07:00:01","2026-09-08 09:15:00"),
 (9,"C-MERIDIAN","U-102","A-1002","CA_DEADLINE","HIGH","PORTAL","CA-5007","2026-09-11 07:00:00","2026-09-11 07:00:01",None),
 (10,"C-MERIDIAN","U-101","A-1001","DOC_AVAILABLE","INFO","PORTAL","D-7001","2026-09-01 05:10:00","2026-09-01 05:10:01","2026-09-01 08:30:00"),
 (11,"C-MERIDIAN","U-102","A-1002","DOC_AVAILABLE","INFO","PORTAL","D-7002","2026-09-01 05:10:00","2026-09-01 05:10:01",None),
 (12,"C-MERIDIAN","U-103","A-1003","DOC_AVAILABLE","INFO","EMAIL","D-7003","2026-09-01 05:10:00","2026-09-01 05:10:02",None),
 (13,"C-HALCYON","U-201","A-2002","CA_DEADLINE","HIGH","PORTAL","CA-5005","2026-09-04 07:00:00","2026-09-04 07:00:01",None),
 (14,"C-HALCYON","U-201","A-2002","CA_DEADLINE","HIGH","EMAIL","CA-5005","2026-09-08 07:00:00","2026-09-08 07:00:02",None),
 (15,"C-HALCYON","U-201","A-2002","CA_DEADLINE","CRITICAL","EMAIL","CA-5005","2026-09-10 07:00:00","2026-09-10 07:00:02",None),   # the DEFAULTED tender: three alerts, zero acks
 (16,"C-HALCYON","U-202","A-2001","NAV_DELAY","HIGH","PORTAL","F-HAL-ETF","2026-09-10 21:05:00","2026-09-10 21:05:01","2026-09-10 21:20:00"),
 (17,"C-HALCYON","U-202","A-2002","NAV_DELAY","HIGH","PORTAL","F-HAL-INC","2026-09-11 18:30:00","2026-09-11 18:30:01",None),
 (18,"C-HALCYON","U-201","A-2001","SETTLEMENT_FAIL","HIGH","WEBHOOK","T-90009","2026-09-11 22:10:00","2026-09-11 22:10:00","2026-09-11 22:10:00"),  # machine-to-machine: instant ack
 (19,"C-HALCYON","U-202",None,"LOGIN_NEW_DEVICE","INFO","EMAIL",None,"2026-09-11 09:47:00","2026-09-11 09:47:02",None),
 (20,"C-HALCYON","U-201","A-2002","DOC_AVAILABLE","INFO","PORTAL","D-7005","2026-09-01 05:10:00","2026-09-01 05:10:01","2026-09-02 14:00:00"),
 (21,"C-ORIENT","U-301","A-3001","SETTLEMENT_FAIL","CRITICAL","PORTAL","T-90011","2026-09-11 06:05:00","2026-09-11 06:05:01","2026-09-11 06:40:00"),
 (22,"C-ORIENT","U-301","A-3001","SETTLEMENT_FAIL","CRITICAL","EMAIL","T-90011","2026-09-11 06:05:00","2026-09-11 06:05:03","2026-09-11 06:40:00"),
 (23,"C-ORIENT","U-302","A-3001","CA_DEADLINE","HIGH","PORTAL","CA-5003","2026-09-09 07:00:00","2026-09-09 07:00:01","2026-09-09 07:30:00"),
 (24,"C-ORIENT","U-301","A-3001","DOC_AVAILABLE","INFO","PORTAL","D-7007","2026-09-01 05:10:00","2026-09-01 05:10:01","2026-09-01 06:00:00"),
 (25,"C-ORIENT","U-303",None,"LOGIN_NEW_DEVICE","INFO","EMAIL",None,"2026-09-11 00:50:00","2026-09-11 00:50:02",None),
]
ins("fact_alerts", alerts)

docs = [
 ("D-7001","C-MERIDIAN","A-1001","STATEMENT","2026-08-31","2026-09-01 04:40:00","2026-09-01 05:10:00","2026-09-01 08:31:00",3,842,"2033-08-31"),
 ("D-7002","C-MERIDIAN","A-1002","STATEMENT","2026-08-31","2026-09-01 04:41:00","2026-09-01 05:10:00",None,0,1210,"2033-08-31"),
 ("D-7003","C-MERIDIAN","A-1003","STATEMENT","2026-08-31","2026-09-01 04:41:00","2026-09-01 05:10:00",None,0,96,"2033-08-31"),
 ("D-7004","C-MERIDIAN","A-1001","CA_NOTICE","2026-09-03","2026-09-03 08:00:00","2026-09-03 08:05:00","2026-09-08 09:16:00",1,220,"2033-09-03"),
 ("D-7010","C-MERIDIAN","A-1002","CA_NOTICE","2026-09-10","2026-09-10 08:00:00","2026-09-10 08:05:00",None,0,240,"2033-09-10"),
 ("D-7011","C-MERIDIAN","A-1001","CONFIRMATION","2026-09-09","2026-09-09 18:30:00","2026-09-09 18:35:00","2026-09-10 08:02:00",1,64,"2033-09-09"),
 ("D-7012","C-MERIDIAN","A-1002","FEE_INVOICE","2026-09-30","2026-09-10 06:00:00",None,None,0,310,"2033-09-30"),   # generated, not yet published
 ("D-7005","C-HALCYON","A-2002","STATEMENT","2026-08-31","2026-09-01 04:42:00","2026-09-01 05:10:00","2026-09-02 14:01:00",2,1530,"2033-08-31"),
 ("D-7006","C-HALCYON","A-2001","NAV_REPORT","2026-09-10","2026-09-10 22:45:00","2026-09-10 22:50:00","2026-09-11 07:10:00",4,410,"2033-09-10"),
 ("D-7013","C-HALCYON","A-2002","CA_NOTICE","2026-08-28","2026-08-28 08:00:00","2026-08-28 08:05:00",None,0,230,"2033-08-28"),   # the tender notice nobody opened
 ("D-7014","C-HALCYON","A-2001","STATEMENT","2026-08-31","2026-09-01 04:42:00","2026-09-01 05:10:00","2026-09-03 10:20:00",1,1490,"2033-08-31"),
 ("D-7007","C-ORIENT","A-3001","STATEMENT","2026-08-31","2026-09-01 04:43:00","2026-09-01 05:10:00","2026-09-01 06:01:00",5,1875,"2036-08-31"),
 ("D-7008","C-ORIENT","A-3001","TAX_RECLAIM","2026-06-30","2026-09-05 12:00:00","2026-09-05 12:30:00",None,0,540,"2036-06-30"),
 ("D-7009","C-ORIENT","A-3001","CA_NOTICE","2026-09-01","2026-09-01 08:00:00","2026-09-01 08:05:00","2026-09-01 08:20:00",2,225,"2036-09-01"),
]
ins("fact_documents", docs)

runs = []
rid = 1
sched = [("U-101","C-MERIDIAN","Holdings","SCHEDULED","XLSX"),("U-201","C-HALCYON","Holdings","SCHEDULED","API"),("U-301","C-ORIENT","Holdings","SCHEDULED","CSV")]
for day in biz:
    for u,c,r,t,f in sched:
        runs.append((rid,u,c,r,t,f"{day} 06:30:00",random.randint(900,2400),random.randint(4,12),f,day)); rid+=1
selfserve = [
 ("U-101","C-MERIDIAN","Settlement Status","SELF_SERVICE","SCREEN","2026-09-11 08:05:00"),
 ("U-101","C-MERIDIAN","Settlement Status","SELF_SERVICE","XLSX","2026-09-11 08:09:00"),
 ("U-102","C-MERIDIAN","Cash Projection","SELF_SERVICE","SCREEN","2026-09-10 09:12:00"),
 ("U-103","C-MERIDIAN","Cash Projection","SELF_SERVICE","PDF","2026-09-10 16:41:00"),
 ("U-101","C-MERIDIAN","CA Calendar","SELF_SERVICE","SCREEN","2026-09-08 09:20:00"),
 ("U-102","C-MERIDIAN","Custom Query","SELF_SERVICE","CSV","2026-09-09 14:33:00"),
 ("U-202","C-HALCYON","NAV Pack","SELF_SERVICE","PDF","2026-09-11 07:12:00"),
 ("U-202","C-HALCYON","NAV Pack","SELF_SERVICE","PDF","2026-09-10 21:22:00"),
 ("U-301","C-ORIENT","Settlement Status","SELF_SERVICE","SCREEN","2026-09-11 06:45:00"),
 ("U-302","C-ORIENT","Cash Projection","SELF_SERVICE","XLSX","2026-09-10 02:45:00"),
 ("U-301","C-ORIENT","CA Calendar","SELF_SERVICE","SCREEN","2026-09-09 07:35:00"),
]
for u,c,r,t,f,at in selfserve:
    runs.append((rid,u,c,r,t,at,random.randint(400,3000),random.randint(3,40),f,at[:10])); rid+=1
# service desk = a State Street person ran the report because the client called or emailed
desk = [
 ("U-201","C-HALCYON","Settlement Status","SERVICE_DESK","XLSX","2026-09-08 15:10:00"),
 ("U-201","C-HALCYON","Settlement Status","SERVICE_DESK","XLSX","2026-09-09 15:40:00"),
 ("U-201","C-HALCYON","Cash Projection","SERVICE_DESK","XLSX","2026-09-10 14:05:00"),
 ("U-201","C-HALCYON","CA Calendar","SERVICE_DESK","PDF","2026-09-10 16:30:00"),
 ("U-201","C-HALCYON","Settlement Status","SERVICE_DESK","XLSX","2026-09-11 15:00:00"),
 ("U-202","C-HALCYON","Holdings","SERVICE_DESK","XLSX","2026-09-11 10:20:00"),
 ("U-102","C-MERIDIAN","Custom Query","SERVICE_DESK","CSV","2026-09-11 11:00:00"),
 ("U-302","C-ORIENT","Holdings","SERVICE_DESK","XLSX","2026-09-04 03:00:00"),
]
for u,c,r,t,f,at in desk:
    runs.append((rid,u,c,r,t,at,random.randint(60000,400000),random.randint(3,40),f,at[:10])); rid+=1
ins("fact_report_runs", runs)

print("\n".join(out))
