#!/usr/bin/env python3
"""Generates seed.sql — deterministic sample data for the Custody Data Lab.
Run once if you want to change the data:  python3 make_seed.py > seed.sql
Business dates: Mon 7 Sep 2026 .. Fri 11 Sep 2026 (as-of date = 2026-09-11)."""
import datetime as dt, random
random.seed(42)

out = []
def w(s=""): out.append(s)
def q(v):
    if v is None: return "NULL"
    if isinstance(v, bool): return "TRUE" if v else "FALSE"
    if isinstance(v, (int, float)): return repr(v)
    return "'" + str(v).replace("'", "''") + "'"
def ins(table, rows):
    w(f"-- {table}: {len(rows)} rows")
    for r in rows: w(f"INSERT INTO {table} VALUES ({', '.join(q(v) for v in r)});")
    w()

w("-- Generated by make_seed.py — sample data for the Custody Data Lab (fictional clients).")
w()

clients = [
 ("C-MERIDIAN","Meridian Pension Trust","Pension fund","GB","Priya Nair"),
 ("C-HALCYON","Halcyon Asset Management","Asset manager","US","Tom Whitfield"),
 ("C-ORIENT","Orient Mutual Insurance","Insurer","JP","Aiko Tanaka"),
]
ins("dim_client", clients)

accounts = [
 ("A-1001","C-MERIDIAN","MER-EQ-01","Meridian Global Equity","USD","Custody","Meridian Pension Trustees Ltd"),
 ("A-1002","C-MERIDIAN","MER-FI-01","Meridian Global Bond","USD","Custody","Meridian Pension Trustees Ltd"),
 ("A-1003","C-MERIDIAN","MER-CASH","Meridian Cash Sweep","USD","Cash","Meridian Pension Trustees Ltd"),
 ("A-2001","C-HALCYON","HAL-ETF-01","Halcyon US Large Cap ETF","USD","Fund","Halcyon Funds Inc"),
 ("A-2002","C-HALCYON","HAL-INC-01","Halcyon Income Fund","USD","Fund","Halcyon Funds Inc"),
 ("A-3001","C-ORIENT","ORI-GEN-01","Orient General Account","JPY","Custody","Orient Mutual Insurance KK"),
]
ins("dim_account", accounts)

securities = [
 ("S-US-AAPL","US0378331005","AAPL","Apple Inc","Equity","US","USD","DTC"),
 ("S-US-MSFT","US5949181045","MSFT","Microsoft Corp","Equity","US","USD","DTC"),
 ("S-JP-7203","JP3633400001","7203","Toyota Motor Corp","Equity","JP","JPY","JASDEC"),
 ("S-DE-SAP","DE0007164600","SAP","SAP SE","Equity","DE","EUR","Clearstream"),
 ("S-US-T34","US91282CJZ59","T 2.5 34","US Treasury 2.5% 2034","Government Bond","US","USD","Fedwire"),
 ("S-DE-BUND31","DE0001102572","BUND 31","Bund 0.5% 2031","Government Bond","DE","EUR","Clearstream"),
 ("S-GB-GILT35","GB00BMBL1F74","GILT 35","UK Gilt 4.25% 2035","Government Bond","GB","GBP","CREST"),
 ("S-US-IBM28","US459200JQ59","IBM 28","IBM 3.3% 2028","Corporate Bond","US","USD","DTC"),
 ("S-US-TBILL","US912797LM10","T-BILL","US T-Bill 3M","Cash Equivalent","US","USD","Fedwire"),
]
ins("dim_security", securities)

# dates: 1 Sep .. 30 Sep 2026
dates = []
d = dt.date(2026, 9, 1)
while d <= dt.date(2026, 9, 30):
    bd = d.weekday() < 5 and d != dt.date(2026, 9, 7)  # 7 Sep 2026 = US Labor Day (holiday)
    dates.append((d.isoformat(), d.year, (d.month-1)//3+1, d.month, d.strftime("%B"), d.strftime("%A"), bd, d == dt.date(2026, 9, 30)))
    d += dt.timedelta(days=1)
ins("dim_date", dates)

funds = [
 ("F-HAL-ETF","Halcyon US Large Cap ETF","C-HALCYON","ETF","16:00"),
 ("F-HAL-INC","Halcyon Income Fund","C-HALCYON","Mutual fund","18:00"),
]
ins("dim_fund", funds)

# ---- positions: business days 8-11 Sep plus 4 Sep, for trend queries
biz = ["2026-09-04","2026-09-08","2026-09-09","2026-09-10","2026-09-11"]
base_px = {"S-US-AAPL":209.5,"S-US-MSFT":418.2,"S-JP-7203":2890.0,"S-DE-SAP":198.4,
           "S-US-T34":97.85,"S-DE-BUND31":91.20,"S-GB-GILT35":99.10,"S-US-IBM28":98.40,"S-US-TBILL":99.05}
fx = {"USD":1.0,"JPY":0.00682,"EUR":1.084,"GBP":1.272}
ccy = {s[0]:s[6] for s in securities}
holdings = {
 "A-1001":{"S-US-AAPL":120000,"S-US-MSFT":95000,"S-JP-7203":800000,"S-DE-SAP":150000,"S-US-TBILL":60000},
 "A-1002":{"S-US-T34":220000000,"S-DE-BUND31":155000000,"S-GB-GILT35":90000000,"S-US-IBM28":80000000},
 "A-1003":{"S-US-TBILL":900000},
 "A-2001":{"S-US-AAPL":410000,"S-US-MSFT":260000},
 "A-2002":{"S-US-T34":150000000,"S-US-IBM28":120000000,"S-US-TBILL":200000},
 "A-3001":{"S-JP-7203":2500000,"S-US-T34":50000000},
}
coupon = {"S-US-T34":2.5,"S-DE-BUND31":0.5,"S-GB-GILT35":4.25,"S-US-IBM28":3.3}
positions = []
drift = {s:1.0 for s in base_px}
for i, day in enumerate(biz):
    for s in base_px:
        drift[s] *= 1 + random.uniform(-0.012, 0.014)
    for acct, hold in holdings.items():
        for s, qty in hold.items():
            px = round(base_px[s]*drift[s], 4)
            f = fx[ccy[s]]
            is_bond = s in coupon or s == "S-US-TBILL"
            mv = round(qty * px/100 * f, 2) if is_bond else round(qty * px * f, 2)
            acc = round(qty * coupon[s]/100 * f * (72+i)/365, 2) if s in coupon else 0.0
            loaded = f"{day} 04:{10+i*3:02d}:00" if not (day=="2026-09-11" and acct=="A-3001") else f"{day} 06:52:00"
            src = "CUSTODY_CORE" if acct != "A-3001" else "SUBCUST_JP"
            positions.append((day, acct, s, qty, px, f, mv, acc, src, loaded))
ins("fact_positions", positions)

txns = [
 (1,"A-1001","2026-09-01","2026-09-01","INJECTION","USD",5000000.00,"Opening cash injection from trustee"),
 (2,"A-1001","2026-09-02","2026-09-03","BUY","USD",-2095000.00,"Buy 10,000 AAPL @ 209.50"),
 (3,"A-1001","2026-09-04","2026-09-04","DIVIDEND","USD",30000.00,"AAPL dividend 0.25/sh on 120,000"),
 (4,"A-1001","2026-09-08","2026-09-09","BUY","USD",-1254600.00,"Buy 3,000 MSFT @ 418.20"),
 (5,"A-1001","2026-09-09","2026-09-09","FX","USD",-412300.00,"FX settle EURUSD for SAP purchase"),
 (6,"A-1001","2026-09-10","2026-09-10","FEE","USD",-18250.00,"Q3 safekeeping fee"),
 (7,"A-1001","2026-09-11","2026-09-12","SELL","USD",578000.00,"Sell 200 Toyota lots"),
 (8,"A-1002","2026-09-01","2026-09-01","INJECTION","USD",12000000.00,"Opening cash injection"),
 (9,"A-1002","2026-09-03","2026-09-03","COUPON","USD",1912500.00,"UK Gilt 4.25% semi-annual coupon"),
 (10,"A-1002","2026-09-08","2026-09-09","BUY","USD",-9785000.00,"Buy 10m US Treasury 2.5% 34 @ 97.85"),
 (11,"A-1002","2026-09-10","2026-09-11","BUY","USD",-4560000.00,"Buy 5m Bund 0.5% 31 @ 91.20"),
 (12,"A-1003","2026-09-01","2026-09-01","INJECTION","USD",25000000.00,"Sweep account funding"),
 (13,"A-1003","2026-09-11","2026-09-11","FEE","USD",-2100.00,"Sweep programme fee"),
 (14,"A-2001","2026-09-09","2026-09-10","SELL","USD",4190000.00,"Sell 20,000 AAPL (redemption funding)"),
 (15,"A-3001","2026-09-10","2026-09-12","BUY","USD",-1976000.00,"Buy 100,000 Toyota @ 2890 JPY"),
]
ins("fact_transactions", txns)

trades = [
 ("T-90001","A-1001","S-US-AAPL","BUY",10000,"2026-09-02","2026-09-03","2026-09-03","SETTLED",None,"Goldman Sachs","2026-09-02 17:42:00"),
 ("T-90002","A-1001","S-US-MSFT","BUY",3000,"2026-09-08","2026-09-09","2026-09-09","SETTLED",None,"Morgan Stanley","2026-09-08 16:05:00"),
 ("T-90003","A-1001","S-DE-SAP","BUY",2000,"2026-09-09","2026-09-11",None,"FAILED","COUNTERPARTY_INSUFFICIENT_SECURITIES","Deutsche Bank","2026-09-09 15:30:00"),
 ("T-90004","A-1001","S-JP-7203","SELL",20000,"2026-09-11","2026-09-14",None,"AFFIRMED",None,"Nomura","2026-09-11 09:12:00"),
 ("T-90005","A-1002","S-US-T34","BUY",10000000,"2026-09-08","2026-09-09","2026-09-09","SETTLED",None,"JP Morgan","2026-09-08 18:20:00"),
 ("T-90006","A-1002","S-DE-BUND31","BUY",5000000,"2026-09-10","2026-09-11",None,"FAILED","INSUFFICIENT_CASH_EUR","BNP Paribas","2026-09-10 14:55:00"),
 ("T-90007","A-1002","S-GB-GILT35","SELL",3000000,"2026-09-11","2026-09-14",None,"MATCHED",None,"Barclays",None),
 ("T-90008","A-2001","S-US-AAPL","SELL",20000,"2026-09-09","2026-09-10","2026-09-10","SETTLED",None,"Citadel Securities","2026-09-09 19:48:00"),
 ("T-90009","A-2001","S-US-MSFT","BUY",5000,"2026-09-11","2026-09-14",None,"PENDING",None,"Jane Street","2026-09-11 21:40:00"),
 ("T-90010","A-2002","S-US-IBM28","BUY",4000000,"2026-09-10","2026-09-11","2026-09-11","SETTLED",None,"Bank of America","2026-09-10 12:10:00"),
 ("T-90011","A-3001","S-JP-7203","BUY",100000,"2026-09-10","2026-09-12",None,"FAILED","SSI_MISMATCH","Daiwa","2026-09-10 08:30:00"),
 ("T-90012","A-3001","S-US-T34","BUY",5000000,"2026-09-11","2026-09-14",None,"PENDING",None,"JP Morgan",None),
]
ins("fact_trades", trades)

cas = [
 ("CA-5001","A-1001","S-US-AAPL","CASH_DIVIDEND",False,"2026-08-20","2026-09-04",None,None,"N/A",120000,30000.00),
 ("CA-5001","A-2001","S-US-AAPL","CASH_DIVIDEND",False,"2026-08-20","2026-09-04",None,None,"N/A",410000,102500.00),
 ("CA-5002","A-1001","S-DE-SAP","TENDER_OFFER",True,"2026-09-03","2026-09-05","2026-09-15","2026-09-17","PENDING",150000,4100000.00),
 ("CA-5003","A-1001","S-JP-7203","DIVIDEND_OPTION",True,"2026-09-01","2026-09-10","2026-09-12","2026-09-16","PENDING",800000,360000.00),
 ("CA-5003","A-3001","S-JP-7203","DIVIDEND_OPTION",True,"2026-09-01","2026-09-10","2026-09-12","2026-09-16","ELECTED",2500000,1125000.00),
 ("CA-5004","A-1002","S-DE-BUND31","COUPON",False,"2026-09-01","2026-09-11",None,None,"N/A",155000000,420000.00),
 ("CA-5005","A-2002","S-US-IBM28","TENDER_OFFER",True,"2026-08-28","2026-09-02","2026-09-10","2026-09-12","DEFAULTED",120000000,2700000.00),
 ("CA-5006","A-1001","S-US-MSFT","STOCK_SPLIT",False,"2026-09-08","2026-09-25",None,None,"N/A",95000,0.00),
 ("CA-5007","A-1002","S-GB-GILT35","RIGHTS_ISSUE",True,"2026-09-10","2026-09-11","2026-09-18","2026-09-22","PENDING",90000000,650000.00),
]
ins("fact_corporate_actions", cas)

navs = []
for f, shares, assets0, liab in [("F-HAL-ETF",42000000,1988000000.0,6200000.0),("F-HAL-INC",18500000,463000000.0,1900000.0)]:
    a = assets0
    for i, day in enumerate(biz):
        bench = round(random.uniform(-0.9, 1.1), 4)
        a = round(a * (1 + bench/100 + random.uniform(-0.05, 0.05)/100), 2)
        nav = round((a - liab)/shares, 4)
        if day == "2026-09-11" and f == "F-HAL-INC":
            navs.append((f, day, a, liab, shares, nav, None, "IN_REVIEW", bench))
        elif day == "2026-09-10" and f == "F-HAL-ETF":
            # a bad price feed: fund moved far more than its market — the classic NAV sanity-check catch
            navs.append((f, day, round(a*1.014,2), liab, shares, round((a*1.014-liab)/shares,4), f"{day} 22:41:00", "PUBLISHED", bench))
        else:
            navs.append((f, day, a, liab, shares, nav, f"{day} 19:{5+i*7:02d}:00", "PUBLISHED", bench))
ins("fact_nav", navs)

print("\n".join(out))
