# Plain-Python explanations, keyed by notebook cell number then by line reference.
PYNOTES = {

2: {
"L1": "<code>import random</code> loads Python's built-in random-numbers module. After this line you write <code>random.something()</code> to use anything inside it.",
"L2": "<code>from copy import deepcopy</code> takes just <em>one</em> name out of a module, so you write <code>deepcopy(x)</code> instead of <code>copy.deepcopy(x)</code>. Two ways of importing; both are normal.",
"L4": "A <strong>list</strong> is an ordered collection written in square brackets. <code>LOCATIONS</code> holds two text values (<strong>strings</strong>). ALL-CAPS is a convention meaning &ldquo;this is a constant, don't change it&rdquo; &mdash; Python does not enforce that, it is just a message to humans.",
"L6": "<code>class</code> defines a new <em>type</em> of thing. Think of it as a blueprint: it says what data every vacuum world holds and what it can do. Making one is called <em>creating an instance</em>, which line 44 does with <code>VacuumEnvironment(seed=1)</code>.",
"L7": "<code>__init__</code> is the <strong>constructor</strong> &mdash; Python runs it automatically when you create an instance. The double underscores mark it as special. <code>self</code> is the instance being built, and it is <em>always</em> the first parameter of a method; you never pass it in yourself. <code>dirt_prob=0.5</code> is a <strong>default value</strong>: callers may leave it out.",
"L8": "<code>random.Random(seed)</code> creates a private random-number generator object and stores it in a plain local variable <code>rng</code>. Because it has no <code>self.</code> in front, it disappears when <code>__init__</code> finishes &mdash; it is only needed during setup.",
"L9": "A <strong>dict</strong> (dictionary) maps keys to values, like a lookup table. This is a <strong>dict comprehension</strong>: <code>{key: value for item in collection}</code> builds one in a single line. Read it right-to-left: for each <code>loc</code> in <code>LOCATIONS</code>, make an entry. The value uses a <strong>conditional expression</strong>: <code>A if condition else B</code> gives <code>A</code> when the condition holds, otherwise <code>B</code>. Anything stored on <code>self.</code> survives after the method ends.",
"L10": "<code>rng.choice(...)</code> picks one random item from a list.",
"L11": "<code>= 0</code> creates the attribute and sets its starting value. Everything after <code>#</code> on a line is a <strong>comment</strong> &mdash; Python ignores it completely.",
"L12": "<code>[]</code> is an empty list, ready to be filled later with <code>.append(...)</code>.",
"L14&ndash;16": "A <strong>method</strong> is just a function defined inside a class. The text in triple quotes on line 15 is a <strong>docstring</strong> &mdash; documentation, not code. Line 16 returns a <strong>tuple</strong>: several values grouped with parentheses and commas. <code>self.status[self.agent_location]</code> is a dict lookup: get the value stored under that key.",
"L18&ndash;19": "This method takes one real argument besides <code>self</code>. Calling it looks like <code>env.execute(&quot;Suck&quot;)</code> &mdash; Python fills in <code>self</code> for you.",
"L20": "Copies the current value into a short local name. Since strings cannot be changed in place, <code>loc</code> keeps the old value even after line 26 changes <code>self.agent_location</code>.",
"L21&ndash;24": "<code>==</code> asks &ldquo;are these equal?&rdquo; (one <code>=</code> assigns, two compare &mdash; a classic beginner trap). <strong>Indentation is how Python groups code</strong>: line 22 is inside line 21's <code>if</code>, and lines 23&ndash;24 are inside line 22's. <code>+=</code> means &ldquo;add to what is already there&rdquo;, so <code>self.performance += 10</code> is short for <code>self.performance = self.performance + 10</code>.",
"L25&ndash;27": "<code>elif</code> is short for &ldquo;else if&rdquo;. Python checks each branch in order and runs only the <em>first</em> one that matches, then skips the rest. <code>-=</code> subtracts in place.",
"L28&ndash;30": "Another <code>elif</code> branch, same shape as the one above it.",
"L31&ndash;32": "<code>pass</code> means &ldquo;do nothing here&rdquo;. Python requires <em>something</em> indented under an <code>if</code>, so <code>pass</code> is the official way to write a deliberately empty block.",
"L33&ndash;34": "<code>else</code> catches everything the branches above missed. <code>raise</code> throws an <strong>exception</strong>, stopping the program with an error. The <code>f</code> before the quotes makes it an <strong>f-string</strong>: anything in <code>{curly braces}</code> is replaced by that variable's value.",
"L36": "<code>.append(...)</code> adds one item to the end of a list. Note the double parentheses: the outer pair belongs to the call, the inner pair builds the tuple being added.",
"L37": "A method may call another method on the same object via <code>self.</code>.",
"L39&ndash;40": "<code>all(...)</code> returns <code>True</code> only if every item is true. Inside it is a <strong>generator expression</strong> &mdash; the same shape as a comprehension but without brackets &mdash; producing one <code>True</code>/<code>False</code> per square. <code>.values()</code> gives just the values of a dict, ignoring the keys.",
"L43&ndash;46": "Creating an instance looks like calling the class: <code>VacuumEnvironment(seed=1)</code>. Writing <code>seed=1</code> is a <strong>keyword argument</strong> &mdash; naming the parameter instead of relying on position. <code>print</code> with several comma-separated values prints them with spaces between.",
},

4: {
"L1&ndash;6": "A dict written out in full, one <code>&quot;key&quot;: &quot;value&quot;</code> pair per line. The trailing comma after the last pair is legal and normal in Python &mdash; it makes adding another line a clean one-line diff.",
"L8&ndash;9": "<code>.items()</code> loops over a dict giving both key and value at once, so <code>for k, v in ...</code> unpacks each pair into two variables. Inside an f-string, the part after the colon is a <strong>format spec</strong>: <code>{k:12s}</code> means &ldquo;this is a string, pad it to 12 characters&rdquo;.",
},

7: {
"L1": "A plain function, not in a class, so no <code>self</code>. Note that <code>agent_program</code> is a <strong>function being passed as an argument</strong> &mdash; in Python functions are ordinary values you can store in variables and hand around.",
"L2": "Creating a new environment instance. <code>seed=seed</code> looks odd but is normal: the left <code>seed</code> is the parameter name in <code>VacuumEnvironment</code>, the right one is this function's variable.",
"L3": "<code>range(steps)</code> produces the numbers 0, 1, 2, &hellip; up to but not including <code>steps</code>. Naming the loop variable <code>_</code> is a convention meaning &ldquo;I must name it, but I never use it&rdquo;.",
"L4": "Calling a method and storing what it returns.",
"L5": "<code>agent_program(p)</code> <em>calls</em> the function that was passed in. This is the payoff of functions-as-values: the harness has no idea which agent it is running.",
"L6": "A call whose return value is ignored &mdash; you only want its side effect on the environment.",
"L7": "Returning several values separated by commas actually returns one tuple. The caller can then unpack it into three variables in one go, as line 1 of the next cell does.",
},

6: {
"L1": "A function that <em>returns another function</em>. This is a <strong>closure</strong>, and it takes a moment to get used to: <code>simple_reflex_agent</code> is not the agent, it <em>builds</em> an agent and hands it back.",
"L2": "A docstring: the first string inside a function is documentation. Triple quotes let it span lines.",
"L3": "A <code>def</code> inside another <code>def</code>. The inner function is defined fresh each time the outer one runs.",
"L4": "<strong>Tuple unpacking.</strong> <code>percept</code> holds a two-item tuple like <code>('A', 'Dirty')</code>; this line splits it into two named variables in one step. Equivalent to <code>location = percept[0]</code> then <code>status = percept[1]</code>, but much easier to read.",
"L5&ndash;6": "<code>return</code> immediately exits the function, so nothing below it runs on this call.",
"L7&ndash;8": "Reached only when the first condition was false.",
"L9&ndash;10": "<code>else</code> with no condition: the catch-all.",
"L11": "<strong>No parentheses here.</strong> <code>return program</code> hands back the function itself; <code>return program()</code> would call it and return its result instead. That one difference is the whole trick.",
},

8: {
"L1": "Unpacking three returned values, using <code>_</code> twice for the two being thrown away. Python allows repeating <code>_</code> like this.",
"L2": "<code>enumerate(trace, 1)</code> pairs each item with a counter starting at 1. The <code>for step, (loc, action, state) in ...</code> unpacks two levels at once: first the counter and the item, then the item's own three parts &mdash; the parentheses mark that nested step.",
"L3": "One f-string with several <code>{}</code> slots. <code>{action:6s}</code> pads to six characters so the columns align.",
},

10: {
"L1": "The same factory-returning-a-closure shape as the previous agent. Getting comfortable with &ldquo;a function that returns a function&rdquo; is most of the work in reading this notebook.",
"L2": "A dict with <code>None</code> as the starting value. <code>None</code> is Python's &ldquo;nothing here yet&rdquo; value &mdash; deliberately different from <code>0</code>, <code>False</code>, or an empty string.",
"L4&ndash;5": "The inner function again, with the same unpacking as before.",
"L6": "Assigning to a dict key either updates it or creates it. Crucially, <code>model</code> belongs to the <em>outer</em> function &mdash; the inner one can read and modify it, and it survives between calls. That is what makes this memory rather than a fresh start each time.",
"L7&ndash;8": "Standard early return.",
"L9&ndash;10": "<code>and</code> is true only when both sides are. Python also short-circuits: if the left side is false it never bothers evaluating the right.",
"L11": "A conditional expression used directly as the return value: <code>return A if condition else B</code>. Same meaning as a four-line if/else, just compact.",
"L12": "Return the inner function, which carries <code>model</code> along with it.",
},

11: {
"L1&ndash;3": "Identical to the previous trace cell. Copying a small block like this rather than wrapping it in a function is normal in notebooks, where each cell is meant to be readable on its own.",
},

13: {
"L1": "Another factory. Every agent in the notebook uses this identical shape, which is what lets the comparison loop treat them interchangeably.",
"L4&ndash;5": "The inner function, and tuple unpacking &mdash; both exactly as in the previous agents.",
"L2": "An empty list. In an <code>if</code>, an empty list counts as <strong>false</strong> and a non-empty one as <strong>true</strong> &mdash; that is what line 9's <code>if not goal_reached_plan</code> relies on.",
"L6": "<code>nonlocal</code> is the subtle one. By default, assigning to a name inside a function creates a <em>new local variable</em>, even if a variable of that name exists outside. <code>nonlocal</code> says &ldquo;no, I mean the one in the enclosing function&rdquo;. Without it, line 11 would build a plan that vanishes the moment the call ends. Note you only need it for <em>assignment</em> &mdash; calling <code>.pop()</code> on line 12 modifies the existing list without rebinding the name, so that would work either way.",
"L7&ndash;8": "Early return, as before.",
"L9&ndash;11": "<code>not</code> flips true and false, so this reads &ldquo;if the plan is empty&rdquo;.",
"L12": "<code>.pop(0)</code> removes the first item from a list <em>and</em> returns it, so the list shrinks as the plan is used up.",
"L13": "Return the closure.",
},

15: {
"L1": "A parameter with a default, so <code>utility_based_agent()</code> and <code>utility_based_agent(battery_start=20)</code> both work.",
"L2": "Why a dict for a single number? Because of the same rule <code>nonlocal</code> exists for: <code>battery = battery - 1</code> inside the inner function would create a new local variable, but <code>battery[&quot;level&quot;] -= 1</code> <em>modifies</em> the existing dict without rebinding the name. Wrapping a value in a dict is a common way to sidestep the issue.",
"L4": "A second inner function. A function can hold as many as it likes, and they can all see the outer function's variables.",
"L5": "Start an accumulator at zero, then adjust it with the rules below.",
"L6&ndash;7": "<code>and</code> requires both conditions. Note these are separate <code>if</code>s, not <code>elif</code>s, so several can apply to the same action and their effects stack.",
"L8&ndash;9": "<code>in</code> tests membership: &ldquo;is <code>action</code> one of these?&rdquo; The parentheses make a tuple; a list would work identically here.",
"L10&ndash;11": "<code>&lt;=</code> is &ldquo;less than or equal to&rdquo;. Two conditions joined with <code>and</code>, so both must hold.",
"L12": "Hand the number back to whoever called this function.",
"L14&ndash;15": "The main program, and the usual unpacking.",
"L16&ndash;17": "A <strong>guard clause</strong>: handle the impossible case first and return, so the rest of the function does not need to worry about it.",
"L18": "A plain list of the options to consider.",
"L19": "Three things at once. <code>max(items, key=f)</code> runs <code>f</code> on every item and returns the <em>item</em> with the highest result &mdash; not the score itself. <code>lambda a: ...</code> is a one-line unnamed function, here taking each candidate as <code>a</code>. And it reads <code>status</code> and <code>battery</code> straight from the enclosing scope without them being passed in.",
"L20&ndash;21": "Membership test again, then subtract one in place.",
"L22&ndash;23": "Return the chosen action; then the outer function returns the program.",
},

17: {
"L1&ndash;2": "<code>{}</code> is an empty dict. Its keys will be <em>tuples</em> &mdash; Python allows that because tuples cannot be changed, and only unchangeable values are allowed as dict keys. (A list could not be used here.)",
"L3": "One dict holding two related values, kept together because they are always updated together.",
"L5&ndash;6": "The percept tuple is stored whole this time, without unpacking &mdash; the agent uses it as a single identifier for &ldquo;the situation I am in&rdquo;.",
"L7": "A list of the actions this agent is allowed to consider.",
"L8&ndash;9": "<code>.setdefault(key, value)</code> means &ldquo;if this key is missing, add it with this value; otherwise leave it alone&rdquo;. It saves writing an <code>if key not in q</code> check. <code>0.0</code> with a decimal point is a <strong>float</strong> (a decimal number) rather than a whole-number <code>int</code>.",
"L11&ndash;12": "<code>is not None</code> is the correct way to test against <code>None</code> &mdash; use <code>is</code> / <code>is not</code> for <code>None</code>, not <code>==</code>.",
"L13": "A conditional expression again: value-if-true, then the condition, then value-if-false. <code>state[1]</code> takes item number 1 from the tuple &mdash; and Python counts from <strong>0</strong>, so index 1 is the <em>second</em> item, the status.",
"L14&ndash;15": "Building a tuple to use as a dict key, then <code>+=</code> on that entry. The maths <code>0.5 * (reward - q[key])</code> moves the stored value halfway toward the reward.",
"L17&ndash;19": "<code>random.random()</code> returns a decimal between 0 and 1, so <code>&lt; 0.1</code> is true roughly 10% of the time &mdash; the standard way to write &ldquo;sometimes&rdquo;.",
"L20&ndash;21": "The <code>max</code>-with-<code>key</code> pattern again, this time looking each action's stored value up in the dict.",
"L23&ndash;25": "Line 23 assigns two variables on one line: the values on the right are matched up with the targets on the left, in order. Then return the action, and return the program.",
},

19: {
"L1&ndash;7": "Re-running a <code>def</code> with the same name simply replaces the old function. No error, no warning &mdash; which is worth knowing, because it also means a typo'd redefinition silently overwrites working code.",
"L10": "<code>random.seed(0)</code> fixes the starting point of the <em>global</em> generator, so any code using <code>random.something()</code> produces the same sequence every run.",
"L11&ndash;17": "A list of tuples &mdash; a very common Python shape for &ldquo;a table of rows&rdquo;. Each row pairs a label with a function. Note the functions are written <em>without</em> parentheses, so they are stored rather than called.",
"L19": "<code>{'Architecture':22s}</code> pads left-aligned to 22 characters; <code>{'Performance':&gt;12s}</code> pads right-aligned to 12. The <code>&gt;</code> is what flips the alignment.",
"L20": "<code>&quot;-&quot; * 46</code> repeats a string 46 times. Multiplying a string by a number is a genuine Python operation.",
"L21&ndash;22": "Looping over a list of tuples unpacks each row into two variables automatically. <code>factory()</code> <em>with</em> parentheses calls it, producing a fresh agent program.",
"L23": "<code>{perf:12d}</code> formats a whole number right-aligned in 12 columns. <code>str(clean)</code> converts <code>True</code>/<code>False</code> into text first, because the <code>s</code> format code needs a string.",
},

24: {
"L1&ndash;6": "Six comment lines. Python ignores everything after a <code>#</code>, so comments cost nothing to run &mdash; they exist purely for whoever reads the code next, including you in a week.",
"L60&ndash;79": "One call to <code>print</code> with a single triple-quoted string spanning twenty lines. Triple quotes (<code>&quot;&quot;&quot;</code>) let a string contain line breaks; everything between them is printed exactly as typed.",
"L8&ndash;9": "<code>class Child(Parent)</code> is <strong>inheritance</strong>: the new class automatically gets every method of the old one, and you override only what should differ. Everything not mentioned here still works exactly as before.",
"L11&ndash;12": "<code>super()</code> means &ldquo;the parent class&rdquo;, so <code>super().__init__(...)</code> runs the original constructor before adding anything new.",
"L13": "Storing a constructor argument as an attribute so the other methods can reach it.",
"L14": "<code>seed + 1000</code> is ordinary arithmetic producing a different seed, and therefore a different sequence of random numbers.",
"L15&ndash;16": "Two counters starting at zero.",
"L18&ndash;19": "Defining a method the parent already has <strong>overrides</strong> it. Calling <code>super().execute(action)</code> first runs the parent's version, then this method adds behaviour on top &mdash; extending rather than replacing.",
"L20&ndash;22": "A <code>for</code> loop over the location names, with an <code>if</code> inside it. <code>and</code> requires both conditions to hold.",
"L23&ndash;24": "<code>sum(...)</code> adds up the values a generator expression produces; <code>1 for v in ... if v == &quot;Clean&quot;</code> yields a 1 for each clean square, so the sum counts them.",
"L25": "Returning a value from the overriding method, matching what the parent returned.",
"L27&ndash;30": "A docstring spanning two lines. <code>/</code> is division and <code>len(...)</code> gives the number of items in a collection.",
"L33&ndash;37": "Several parameters with defaults. Line 36 nests calls: <code>env.percept()</code> runs first, its result goes into <code>agent_program(...)</code>, and that result goes into <code>env.execute(...)</code> &mdash; innermost first, always.",
"L40": "Assigning two variables on one line. <code>range(8)</code> is stored for reuse rather than looped over immediately.",
"L41&ndash;47": "Line 45 wraps a call in <code>lambda:</code> with no arguments. Writing <code>utility_based_agent(battery_start=STEPS)</code> directly would call it <em>now</em>; wrapping it in a lambda stores it to be called later, matching the other rows which hold uncalled functions.",
"L49&ndash;50": "Header formatting, same technique as the earlier comparison cell.",
"L51&ndash;55": "A loop inside a loop. The inner one runs every seed; <code>results.append(...)</code> collects each outcome into the list created on line 52.",
"L56&ndash;58": "<code>r[0]</code> takes the first item of each tuple. <code>sum(...) / len(...)</code> is how you average a list in plain Python. <code>{clean:16.0%}</code> multiplies by 100 and appends a percent sign, with <code>.0</code> meaning no decimal places.",
"L82&ndash;83": "Backticks inside a docstring are just characters &mdash; Python has no special meaning for them; that is a convention borrowed from Markdown.",
"L84&ndash;86": "<code>-10**9</code> is negative ten to the ninth power. <code>**</code> is exponentiation, not multiplication.",
"L88&ndash;92": "Reading a dict entry, adding to it, and writing it back.",
"L93&ndash;94": "Early return.",
"L95&ndash;98": "<code>all(...)</code> with a generator expression spread over several lines &mdash; legal because the open bracket on line 95 is not closed until line 98, and Python ignores line breaks inside brackets.",
"L99&ndash;101": "A boolean variable used directly as a condition. Writing <code>if believed_clean</code> is preferred over <code>if believed_clean == True</code>.",
"L105&ndash;108": "Line 105 is a <strong>list comprehension</strong>: <code>[expression for item in collection]</code> builds a list in one line. Lines 106&ndash;108 are three f-strings written next to each other with no operator between them &mdash; Python automatically joins adjacent string literals into one. <code>\\n</code> is an escape sequence meaning a newline character.",
},

26: {
"L1&ndash;4": "Comment lines setting up what this cell does. The <code>#</code> makes Python skip the rest of the line entirely.",
"L71&ndash;87": "A single <code>print</code> of one long triple-quoted string. The <code>*</code> at the start of several lines is just a character &mdash; Python attaches no meaning to it inside a string.",
"L6&ndash;10": "A subclass overriding a single method. Everything else &mdash; the constructor, <code>execute</code>, <code>is_clean</code> &mdash; is inherited untouched.",
"L13&ndash;17": "The same runner shape as before, with a different environment class inside.",
"L21&ndash;25": "Note the parameter is now <code>status</code>, not <code>percept</code>: the inner function's parameter name is entirely up to you, and here it is renamed to reflect that a bare string arrives rather than a tuple. Line 24 returns a conditional expression directly.",
"L29&ndash;35": "The docstring spans two lines. Line 32 creates a private generator so this agent's coin flips do not disturb anyone else's random numbers.",
"L39&ndash;43": "A four-line docstring. The <code>*</code> characters inside it are just text.",
"L44": "One dict holding three different things &mdash; a quick alternative to defining a small class.",
"L46&ndash;49": "Reading a dict value into a local variable, then an <code>is not None</code> test. Line 49 uses a variable as the dict key, which is why the belief can be recorded against whichever square the agent thinks it is on.",
"L50&ndash;53": "An <code>if</code> nested inside another <code>if</code> &mdash; the deeper indentation is what marks the nesting.",
"L54&ndash;56": "<code>is None</code> tests for the &ldquo;nothing yet&rdquo; value.",
"L57&ndash;58": "Two equality tests joined with <code>and</code>.",
"L59&ndash;60": "Two conditional expressions in a row: one assigns, the next returns.",
"L64&ndash;69": "Looping directly over a list of tuples written inline in the <code>for</code> statement. Line 68 is a <strong>join</strong>: <code>&quot; &quot;.join(...)</code> glues a sequence of strings together with a space between each. The <code>a for _, a, _ in trace</code> inside it pulls out only the middle item of each triple, discarding the other two with <code>_</code>.",
},

28: {
"L1&ndash;7": "Lines 1&ndash;5 are comments &mdash; everything after <code>#</code> is ignored by Python, so a block like this is free to write. Line 7 creates a new module-level list; nothing stops you having several.",
"L18&ndash;19": "Two more attributes initialised to empty starting values, exactly as in the original class.",
"L10&ndash;11": "<code>class RowVacuumEnvironment:</code> with no parentheses means it inherits nothing &mdash; a fresh start rather than a subclass.",
"L13&ndash;16": "<code>locations=ROW</code> gives a list as a default value. Line 15's <code>list(locations)</code> makes a <em>copy</em>, which matters: without it, the instance and the caller would share one list, and changing either would change both.",
"L17": "<code>rng.randrange(n)</code> returns a whole number from 0 up to n&minus;1 &mdash; exactly the valid index range for a list of length n.",
"L21&ndash;23": "<code>@property</code> is a <strong>decorator</strong> &mdash; a line starting with <code>@</code> that modifies the function below it. This one lets you write <code>env.agent_location</code> with no parentheses, even though it is really a method being run. It is how you replace a stored attribute with a computed one without changing any code that reads it.",
"L25&ndash;26": "Note it calls the property by name, no parentheses &mdash; that is the point of line 21.",
"L28&ndash;33": "Unchanged from the original class. Repeating code rather than inheriting is a deliberate trade here: more duplication, but each class reads on its own.",
"L34&ndash;36": "<code>max(0, self.index - 1)</code> takes the larger of the two, so the result can never drop below 0. It is the idiomatic Python way to clamp a lower bound &mdash; no <code>if</code> needed.",
"L37&ndash;39": "<code>min(...)</code> is the mirror image, clamping the upper bound at the last valid index.",
"L40&ndash;43": "The same <code>pass</code> and <code>raise</code> pattern as the original.",
"L44&ndash;45": "<code>dict(self.status)</code> makes a copy of a dict &mdash; a <em>shallow</em> one, meaning it copies the entries but not the values inside them. Here the values are plain strings, which cannot change, so shallow is enough and <code>deepcopy</code> would be wasted work.",
"L47&ndash;55": "Familiar shapes: <code>all()</code> with a generator, then a loop calling the agent.",
"L58&ndash;66": "<code>locations[-1]</code> is <strong>negative indexing</strong>: &minus;1 means the last item, &minus;2 the second-to-last. Much cleaner than <code>locations[len(locations) - 1]</code>.",
"L69&ndash;73": "Two pieces of state in the closure this time. Line 72 builds a dict from a list with a comprehension.",
"L75&ndash;80": "The usual observe-then-act shape.",
"L81&ndash;82": "<code>all()</code> over <code>.values()</code>. Note that <code>None</code> is not equal to <code>&quot;Clean&quot;</code>, so an unvisited square makes this false automatically &mdash; no extra check needed.",
"L83&ndash;87": "<code>locations[0]</code> is the first item. Assigning into the <code>direction</code> dict changes state that persists to the next call.",
"L91&ndash;96": "Line 95 mixes formats: <code>{perf:4d}</code> pads a number to 4 columns, <code>{str(clean):5s}</code> converts then pads. Line 96's <code>{'':20s}</code> prints 20 spaces &mdash; a quick way to indent under the previous line.",
"L98&ndash;108": "A multi-line string passed straight to <code>print</code>. Everything inside the triple quotes appears exactly as written, line breaks included.",
"L110&ndash;118": "<code>ord(&quot;A&quot;)</code> gives the numeric code for the letter A, and <code>chr(...)</code> turns a number back into a letter &mdash; so <code>chr(ord(&quot;A&quot;) + i)</code> generates A, B, C, D&hellip; Line 116 multiplies inside <code>range</code>, which is fine since it is just arithmetic.",
"L120&ndash;128": "Another multi-line string.",
"L131&ndash;137": "Line 135 unpacks a tuple but keeps only the second part, discarding the first with <code>_</code>.",
"L140&ndash;151": "Line 142 assigns two variables at once, one a number and one a list. Line 148 uses <code>cleaned += env.is_clean()</code> &mdash; in Python <code>True</code> equals 1 and <code>False</code> equals 0, so adding booleans counts how many were true. Line 150&ndash;151 splits one f-string across two lines by placing them next to each other inside the call's parentheses.",
"L153&ndash;157": "A final multi-line string.",
},

30: {
"L1&ndash;14": "Fourteen comment lines. A block like this at the top of a cell is a normal way to record <em>why</em> the code below looks the way it does &mdash; something the code itself cannot say.",
"L16&ndash;17": "A parameter list too long for one line, wrapped inside the parentheses. Python allows line breaks freely inside any bracket, so no continuation character is needed.",
"L18&ndash;20": "Three dicts holding the agent's state. Line 19 builds one with a comprehension, giving every square the same starting value.",
"L22&ndash;24": "<code>decay ** (t - deadline)</code> is exponentiation: <code>0.6 ** 3</code> is 0.6&times;0.6&times;0.6. Combined with a conditional expression, the whole calculation fits on one line.",
"L26&ndash;33": "Several <code>if</code>s each returning early, so by line 32 you know neither earlier case applied. Line 33's <code>1 - (1 - p) ** age</code> is the standard &ldquo;probability it happened at least once in <code>age</code> tries&rdquo;.",
"L35&ndash;37": "Line 37 is a conditional expression whose true-branch is itself a calculation. It reads: return <code>10 * time_factor(t)</code> if the square is dirty, otherwise <code>-0.5</code>.",
"L38&ndash;42": "Line 39 picks a destination with another conditional expression. Line 42 stores an intermediate result in <code>u</code> so the next lines can adjust it before returning &mdash; easier to read than one enormous expression.",
"L43&ndash;45": "Adjust the accumulated value, then return it.",
"L46": "A bare <code>return 0.0</code> reached only when none of the earlier branches returned &mdash; the fall-through case.",
"L48&ndash;52": "Reading and writing dict entries, including using a variable as the key.",
"L53&ndash;54": "A guard clause returning early.",
"L55&ndash;57": "Lines 55&ndash;56 are a dict comprehension whose values come from calling a function, spread across two lines inside the braces. Line 57's <code>max(scores, key=scores.get)</code> is a neat idiom. Looping over a dict gives its <em>keys</em>, and <code>scores.get</code> is the lookup method passed as a function without calling it &mdash; so this reads &ldquo;of all the keys, give me the one whose value is largest&rdquo;.",
"L58&ndash;61": "<code>if verbose:</code> uses a boolean flag directly. Line 59 joins formatted strings with two spaces; <code>{scores[a]:+6.1f}</code> means always show the sign (<code>+</code>), pad to 6 characters, one decimal place, floating point. Line 61 nests quotes carefully: <code>state['t']</code> uses single quotes because the f-string itself uses double.",
"L62&ndash;66": "Two separate <code>if</code>s, so both can apply on the same step.",
"L70&ndash;76": "Line 71 is an f-string with no placeholders, which is harmless. <code>\\n</code> inserts a line break. Line 76's <code>{...:.0%}</code> formats a fraction as a whole-number percentage.",
"L78&ndash;89": "A loop over a tuple of values, containing another loop over 60 seeds. Line 87 appends a tuple, so <code>results</code> becomes a list of pairs. Lines 88&ndash;89 are two adjacent f-strings joined automatically.",
"L91&ndash;106": "One long multi-line string.",
},
}
