-- STEP 5 — the numbers a VP looks at every month.
USE ROLE ACCOUNTADMIN; USE WAREHOUSE LAB_WH;

-- 5a. Credits burned per warehouse, last 7 days. (ACCOUNT_USAGE views lag by up to 2 hours.)
SELECT WAREHOUSE_NAME, DATE_TRUNC('day', START_TIME) AS day, ROUND(SUM(CREDITS_USED), 3) AS credits
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
WHERE START_TIME > DATEADD('day', -7, CURRENT_TIMESTAMP())
GROUP BY 1, 2 ORDER BY 2 DESC, 1;

-- 5b. The most expensive queries, and who ran them.
SELECT USER_NAME, ROLE_NAME, WAREHOUSE_NAME, TOTAL_ELAPSED_TIME/1000 AS seconds, BYTES_SCANNED/1e6 AS mb_scanned, LEFT(QUERY_TEXT, 80) AS query
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE START_TIME > DATEADD('day', -7, CURRENT_TIMESTAMP()) AND WAREHOUSE_NAME IS NOT NULL
ORDER BY TOTAL_ELAPSED_TIME DESC LIMIT 10;

-- 5c. Who has access to what: the entitlement review for your own platform.
SELECT GRANTEE_NAME AS role, PRIVILEGE, TABLE_CATALOG, TABLE_SCHEMA, NAME AS object
FROM SNOWFLAKE.ACCOUNT_USAGE.GRANTS_TO_ROLES
WHERE DELETED_ON IS NULL AND TABLE_CATALOG = 'CUSTODY_LAB' ORDER BY 1, 4, 5;

-- 5d. Storage: how big is the lab, really? (Compressed; the answer is a few MB.)
SELECT TABLE_SCHEMA, TABLE_NAME, ROUND(ACTIVE_BYTES/1024, 1) AS kb
FROM SNOWFLAKE.ACCOUNT_USAGE.TABLE_STORAGE_METRICS
WHERE TABLE_CATALOG = 'CUSTODY_LAB' AND ACTIVE_BYTES > 0 ORDER BY 3 DESC;

-- 5e. The experiment: leave LAB_WH running with AUTO_SUSPEND = 0 for one hour, then rerun 5a. That is the zombie-warehouse cost.
-- ALTER WAREHOUSE LAB_WH SET AUTO_SUSPEND = 0;   ...one hour later...   ALTER WAREHOUSE LAB_WH SET AUTO_SUSPEND = 60;
